[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "ms-excel-win"
version = "0.1.0"
description = "Excel integration using xlOil for MainSequence"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
  "xloil>=0.21",
  "mainsequence",
  "pandas",
  "requests",
  "pillow",
  "debugpy"
]

[tool.hatch.build.targets.wheel]
packages = ["src/ms_excel_win"]

[tool.uv]
package = true
